options(vsc.plot = "Active")
options(vsc.browser = "Active")
options(vsc.viewer = "Active")
options(vsc.page_viewer = "Active")
options(vsc.view = "Active")
options(vsc.helpPanel = "Active")
options(vsc.dev.args = list(width = 10, height = 8, units = "in", res = 300))
source(file.path(Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"), ".vscode-R", "init.R"))